### ISSUE TITLE
Update to work with 12.1 and WIYN+WHIRC data

### ISSUE THREAD

**Issue by wmwv** [mwvgroup/wiyn_lsst#2]
Update to work with 12.1 and WIYN+WHIRC data

Errors that happen are
```
python/lsst/meas/base/baseLib_wrap.cc:44109:53: error: no member named 'logging' in namespace 'lsst::pex'
```

**Comment by wmwv** [comment]
Works now.  Follow directions in README:

```
Processing of SweetSpot WIYN images using LSST DM Stack.

Requires the definition of the environment variable DR1BASE and the existence of SweetSpot stacks in ${DR1BASE}/stacks.

1. Create LSST-formatted FITS with image, weight map, and mask.
`sh make_wiyn_dr1_lsst.sh`
2. Ingest files
`sh ingest_wiyn_dr1_images.sh`
3. processCcd files
`sh run_wiyn.sh`
4. Run subtractions
`python sub_wiyn_dr1.py`
5. Generate coordinate files for forced photometry
`sh make_coord_files.sh`
6. Run lightcurves on subtractions
`python wiyn_forcedPhotExternalCatalog.py`
```
